[package]
name = "binextract"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytemuck = { version = "1.24.0", features = ["derive"] }
byteorder = "1.5.0"
lexopt = "0.3.1"
png = "0.18.0"
